package models;
// Generated 17.12.2017 14:21:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BookCatalog generated by hbm2java
 */
public class BookCatalog  implements java.io.Serializable {


     private Integer idBook;
     private String name;
     private String author;
     private String genre;
     private Integer year;
     private Integer cost;
     private String description;
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<Basket> baskets = new HashSet<Basket>(0);

    public BookCatalog() {
    }

	
    public BookCatalog(String name, String author, String genre, Integer year, Integer cost) {
        this.name = name;
        this.author = author;
        this.genre = genre;
        this.year = year;
        this.cost = cost;
    }
    public BookCatalog(String name, String author, String genre, Integer year, Integer cost, String description, Set<Orders> orderses, Set<Basket> baskets) {
       this.name = name;
       this.author = author;
       this.genre = genre;
       this.year = year;
       this.cost = cost;
       this.description = description;
       this.orderses = orderses;
       this.baskets = baskets;
    }
   
    public Integer getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(Integer idBook) {
        this.idBook = idBook;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getCost() {
        return this.cost;
    }
    
    public void setCost(Integer cost) {
        this.cost = cost;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }
    public Set<Basket> getBaskets() {
        return this.baskets;
    }
    
    public void setBaskets(Set<Basket> baskets) {
        this.baskets = baskets;
    }




}


