package models;
// Generated 17.12.2017 14:21:14 by Hibernate Tools 4.3.1


import java.sql.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer idOrder;
     private BookCatalog bookCatalog;
     private Users users;
     private Date dataSale;

    public Orders() {
    }

    public Orders(BookCatalog bookCatalog, Users users, Date dataSale) {
       this.bookCatalog = bookCatalog;
       this.users = users;
       this.dataSale = dataSale;
    }
   
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }
    public BookCatalog getBookCatalog() {
        return this.bookCatalog;
    }
    
    public void setBookCatalog(BookCatalog bookCatalog) {
        this.bookCatalog = bookCatalog;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDataSale() {
        return this.dataSale;
    }
    
    public void setDataSale(Date dataSale) {
        this.dataSale = dataSale;
    }




}


